/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// An existing category.
    /// </summary>
    [DataContract(Name = "Category.Models.Read.Category")]
    public partial class CategoryModelsReadCategory : IEquatable<CategoryModelsReadCategory>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CategoryModelsReadCategory" /> class.
        /// </summary>
        /// <param name="categoryId">The unique identifier for the category..</param>
        /// <param name="parentCategoryId">The unique identifier for the parent category..</param>
        /// <param name="names">The localizable names of the category..</param>
        /// <param name="descriptions">The localized descriptions of the category..</param>
        /// <param name="googleCategoryPath">The Google Taxonomy category path for the category, if any..</param>
        public CategoryModelsReadCategory(int categoryId = default(int), int parentCategoryId = default(int), List<SharedModelsLocalizableContent> names = default(List<SharedModelsLocalizableContent>), List<SharedModelsLocalizableContent> descriptions = default(List<SharedModelsLocalizableContent>), string googleCategoryPath = default(string))
        {
            this.CategoryId = categoryId;
            this.ParentCategoryId = parentCategoryId;
            this.Names = names;
            this.Descriptions = descriptions;
            this.GoogleCategoryPath = googleCategoryPath;
        }

        /// <summary>
        /// The unique identifier for the category.
        /// </summary>
        /// <value>The unique identifier for the category.</value>
        [DataMember(Name = "CategoryId", EmitDefaultValue = false)]
        public int CategoryId { get; set; }

        /// <summary>
        /// The unique identifier for the parent category.
        /// </summary>
        /// <value>The unique identifier for the parent category.</value>
        [DataMember(Name = "ParentCategoryId", EmitDefaultValue = false)]
        public int ParentCategoryId { get; set; }

        /// <summary>
        /// The localizable names of the category.
        /// </summary>
        /// <value>The localizable names of the category.</value>
        [DataMember(Name = "Names", EmitDefaultValue = false)]
        public List<SharedModelsLocalizableContent> Names { get; set; }

        /// <summary>
        /// The localized descriptions of the category.
        /// </summary>
        /// <value>The localized descriptions of the category.</value>
        [DataMember(Name = "Descriptions", EmitDefaultValue = false)]
        public List<SharedModelsLocalizableContent> Descriptions { get; set; }

        /// <summary>
        /// The Google Taxonomy category path for the category, if any.
        /// </summary>
        /// <value>The Google Taxonomy category path for the category, if any.</value>
        [DataMember(Name = "GoogleCategoryPath", EmitDefaultValue = false)]
        public string GoogleCategoryPath { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CategoryModelsReadCategory {\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  ParentCategoryId: ").Append(ParentCategoryId).Append("\n");
            sb.Append("  Names: ").Append(Names).Append("\n");
            sb.Append("  Descriptions: ").Append(Descriptions).Append("\n");
            sb.Append("  GoogleCategoryPath: ").Append(GoogleCategoryPath).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CategoryModelsReadCategory);
        }

        /// <summary>
        /// Returns true if CategoryModelsReadCategory instances are equal
        /// </summary>
        /// <param name="input">Instance of CategoryModelsReadCategory to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CategoryModelsReadCategory input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CategoryId == input.CategoryId ||
                    this.CategoryId.Equals(input.CategoryId)
                ) && 
                (
                    this.ParentCategoryId == input.ParentCategoryId ||
                    this.ParentCategoryId.Equals(input.ParentCategoryId)
                ) && 
                (
                    this.Names == input.Names ||
                    this.Names != null &&
                    input.Names != null &&
                    this.Names.SequenceEqual(input.Names)
                ) && 
                (
                    this.Descriptions == input.Descriptions ||
                    this.Descriptions != null &&
                    input.Descriptions != null &&
                    this.Descriptions.SequenceEqual(input.Descriptions)
                ) && 
                (
                    this.GoogleCategoryPath == input.GoogleCategoryPath ||
                    (this.GoogleCategoryPath != null &&
                    this.GoogleCategoryPath.Equals(input.GoogleCategoryPath))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.CategoryId.GetHashCode();
                hashCode = (hashCode * 59) + this.ParentCategoryId.GetHashCode();
                if (this.Names != null)
                {
                    hashCode = (hashCode * 59) + this.Names.GetHashCode();
                }
                if (this.Descriptions != null)
                {
                    hashCode = (hashCode * 59) + this.Descriptions.GetHashCode();
                }
                if (this.GoogleCategoryPath != null)
                {
                    hashCode = (hashCode * 59) + this.GoogleCategoryPath.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
