/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A stock value for a product item
    /// </summary>
    [DataContract(Name = "Product.Models.Read.ProductItemStock")]
    public partial class ProductModelsReadProductItemStock : IEquatable<ProductModelsReadProductItemStock>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductModelsReadProductItemStock" /> class.
        /// </summary>
        /// <param name="itemId">A value to uniquely identity a single product item..</param>
        /// <param name="stock">The physical stock value..</param>
        /// <param name="stockOversellable">The oversellable stock value..</param>
        /// <param name="stockStatic">The static stock value..</param>
        /// <param name="stockSellable">The sellable stock value..</param>
        public ProductModelsReadProductItemStock(int itemId = default(int), int stock = default(int), int stockOversellable = default(int), int stockStatic = default(int), int stockSellable = default(int))
        {
            this.ItemId = itemId;
            this.Stock = stock;
            this.StockOversellable = stockOversellable;
            this.StockStatic = stockStatic;
            this.StockSellable = stockSellable;
        }

        /// <summary>
        /// A value to uniquely identity a single product item.
        /// </summary>
        /// <value>A value to uniquely identity a single product item.</value>
        [DataMember(Name = "ItemId", EmitDefaultValue = false)]
        public int ItemId { get; set; }

        /// <summary>
        /// The physical stock value.
        /// </summary>
        /// <value>The physical stock value.</value>
        [DataMember(Name = "Stock", EmitDefaultValue = false)]
        public int Stock { get; set; }

        /// <summary>
        /// The oversellable stock value.
        /// </summary>
        /// <value>The oversellable stock value.</value>
        [DataMember(Name = "StockOversellable", EmitDefaultValue = false)]
        public int StockOversellable { get; set; }

        /// <summary>
        /// The static stock value.
        /// </summary>
        /// <value>The static stock value.</value>
        [DataMember(Name = "StockStatic", EmitDefaultValue = false)]
        public int StockStatic { get; set; }

        /// <summary>
        /// The sellable stock value.
        /// </summary>
        /// <value>The sellable stock value.</value>
        [DataMember(Name = "StockSellable", EmitDefaultValue = false)]
        public int StockSellable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductModelsReadProductItemStock {\n");
            sb.Append("  ItemId: ").Append(ItemId).Append("\n");
            sb.Append("  Stock: ").Append(Stock).Append("\n");
            sb.Append("  StockOversellable: ").Append(StockOversellable).Append("\n");
            sb.Append("  StockStatic: ").Append(StockStatic).Append("\n");
            sb.Append("  StockSellable: ").Append(StockSellable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProductModelsReadProductItemStock);
        }

        /// <summary>
        /// Returns true if ProductModelsReadProductItemStock instances are equal
        /// </summary>
        /// <param name="input">Instance of ProductModelsReadProductItemStock to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductModelsReadProductItemStock input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ItemId == input.ItemId ||
                    this.ItemId.Equals(input.ItemId)
                ) && 
                (
                    this.Stock == input.Stock ||
                    this.Stock.Equals(input.Stock)
                ) && 
                (
                    this.StockOversellable == input.StockOversellable ||
                    this.StockOversellable.Equals(input.StockOversellable)
                ) && 
                (
                    this.StockStatic == input.StockStatic ||
                    this.StockStatic.Equals(input.StockStatic)
                ) && 
                (
                    this.StockSellable == input.StockSellable ||
                    this.StockSellable.Equals(input.StockSellable)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ItemId.GetHashCode();
                hashCode = (hashCode * 59) + this.Stock.GetHashCode();
                hashCode = (hashCode * 59) + this.StockOversellable.GetHashCode();
                hashCode = (hashCode * 59) + this.StockStatic.GetHashCode();
                hashCode = (hashCode * 59) + this.StockSellable.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
