/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing EnvelopeProductParameterModelsReadProductParameterPredefinedValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnvelopeProductParameterModelsReadProductParameterPredefinedValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnvelopeProductParameterModelsReadProductParameterPredefinedValue
        //private EnvelopeProductParameterModelsReadProductParameterPredefinedValue instance;

        public EnvelopeProductParameterModelsReadProductParameterPredefinedValueTests()
        {
            // TODO uncomment below to create an instance of EnvelopeProductParameterModelsReadProductParameterPredefinedValue
            //instance = new EnvelopeProductParameterModelsReadProductParameterPredefinedValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnvelopeProductParameterModelsReadProductParameterPredefinedValue
        /// </summary>
        [Fact]
        public void EnvelopeProductParameterModelsReadProductParameterPredefinedValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnvelopeProductParameterModelsReadProductParameterPredefinedValue
            //Assert.IsType<EnvelopeProductParameterModelsReadProductParameterPredefinedValue>(instance);
        }


        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Fact]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }
        /// <summary>
        /// Test the property 'PageResult'
        /// </summary>
        [Fact]
        public void PageResultTest()
        {
            // TODO unit test for the property 'PageResult'
        }

    }

}
