/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCapture
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCaptureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCapture
        //private OrderCapture instance;

        public OrderCaptureTests()
        {
            // TODO uncomment below to create an instance of OrderCapture
            //instance = new OrderCapture();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCapture
        /// </summary>
        [Fact]
        public void OrderCaptureInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCapture
            //Assert.IsType<OrderCapture>(instance);
        }


        /// <summary>
        /// Test the property 'CaptureId'
        /// </summary>
        [Fact]
        public void CaptureIdTest()
        {
            // TODO unit test for the property 'CaptureId'
        }
        /// <summary>
        /// Test the property 'OrderPaymentId'
        /// </summary>
        [Fact]
        public void OrderPaymentIdTest()
        {
            // TODO unit test for the property 'OrderPaymentId'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'ExternalOrderId'
        /// </summary>
        [Fact]
        public void ExternalOrderIdTest()
        {
            // TODO unit test for the property 'ExternalOrderId'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ProcessedOn'
        /// </summary>
        [Fact]
        public void ProcessedOnTest()
        {
            // TODO unit test for the property 'ProcessedOn'
        }
        /// <summary>
        /// Test the property 'CapturedItemTotal'
        /// </summary>
        [Fact]
        public void CapturedItemTotalTest()
        {
            // TODO unit test for the property 'CapturedItemTotal'
        }
        /// <summary>
        /// Test the property 'CapturedShippingFee'
        /// </summary>
        [Fact]
        public void CapturedShippingFeeTest()
        {
            // TODO unit test for the property 'CapturedShippingFee'
        }
        /// <summary>
        /// Test the property 'CapturedPaymentFee'
        /// </summary>
        [Fact]
        public void CapturedPaymentFeeTest()
        {
            // TODO unit test for the property 'CapturedPaymentFee'
        }
        /// <summary>
        /// Test the property 'CapturedDiscount'
        /// </summary>
        [Fact]
        public void CapturedDiscountTest()
        {
            // TODO unit test for the property 'CapturedDiscount'
        }
        /// <summary>
        /// Test the property 'CapturedBalance'
        /// </summary>
        [Fact]
        public void CapturedBalanceTest()
        {
            // TODO unit test for the property 'CapturedBalance'
        }
        /// <summary>
        /// Test the property 'VatRate'
        /// </summary>
        [Fact]
        public void VatRateTest()
        {
            // TODO unit test for the property 'VatRate'
        }
        /// <summary>
        /// Test the property 'TrackingNumber'
        /// </summary>
        [Fact]
        public void TrackingNumberTest()
        {
            // TODO unit test for the property 'TrackingNumber'
        }
        /// <summary>
        /// Test the property 'ShippingName'
        /// </summary>
        [Fact]
        public void ShippingNameTest()
        {
            // TODO unit test for the property 'ShippingName'
        }
        /// <summary>
        /// Test the property 'TrackingUri'
        /// </summary>
        [Fact]
        public void TrackingUriTest()
        {
            // TODO unit test for the property 'TrackingUri'
        }
        /// <summary>
        /// Test the property 'ShippingMethod'
        /// </summary>
        [Fact]
        public void ShippingMethodTest()
        {
            // TODO unit test for the property 'ShippingMethod'
        }
        /// <summary>
        /// Test the property 'PaymentName'
        /// </summary>
        [Fact]
        public void PaymentNameTest()
        {
            // TODO unit test for the property 'PaymentName'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
        /// <summary>
        /// Test the property 'Rows'
        /// </summary>
        [Fact]
        public void RowsTest()
        {
            // TODO unit test for the property 'Rows'
        }
        /// <summary>
        /// Test the property 'OrderTransactionId'
        /// </summary>
        [Fact]
        public void OrderTransactionIdTest()
        {
            // TODO unit test for the property 'OrderTransactionId'
        }
        /// <summary>
        /// Test the property 'SecondaryOrderTransactionId'
        /// </summary>
        [Fact]
        public void SecondaryOrderTransactionIdTest()
        {
            // TODO unit test for the property 'SecondaryOrderTransactionId'
        }

    }

}
