/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderModelsOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderModelsOrderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderModelsOrder
        //private OrderModelsOrder instance;

        public OrderModelsOrderTests()
        {
            // TODO uncomment below to create an instance of OrderModelsOrder
            //instance = new OrderModelsOrder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderModelsOrder
        /// </summary>
        [Fact]
        public void OrderModelsOrderInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderModelsOrder
            //Assert.IsType<OrderModelsOrder>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'PersonalId'
        /// </summary>
        [Fact]
        public void PersonalIdTest()
        {
            // TODO unit test for the property 'PersonalId'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'CustomerTypeId'
        /// </summary>
        [Fact]
        public void CustomerTypeIdTest()
        {
            // TODO unit test for the property 'CustomerTypeId'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'CurrencyRate'
        /// </summary>
        [Fact]
        public void CurrencyRateTest()
        {
            // TODO unit test for the property 'CurrencyRate'
        }
        /// <summary>
        /// Test the property 'MarketId'
        /// </summary>
        [Fact]
        public void MarketIdTest()
        {
            // TODO unit test for the property 'MarketId'
        }
        /// <summary>
        /// Test the property 'MarketName'
        /// </summary>
        [Fact]
        public void MarketNameTest()
        {
            // TODO unit test for the property 'MarketName'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'OrderTotal'
        /// </summary>
        [Fact]
        public void OrderTotalTest()
        {
            // TODO unit test for the property 'OrderTotal'
        }
        /// <summary>
        /// Test the property 'ExpectedSum'
        /// </summary>
        [Fact]
        public void ExpectedSumTest()
        {
            // TODO unit test for the property 'ExpectedSum'
        }
        /// <summary>
        /// Test the property 'VATTotal'
        /// </summary>
        [Fact]
        public void VATTotalTest()
        {
            // TODO unit test for the property 'VATTotal'
        }
        /// <summary>
        /// Test the property 'OrderValueIncVat'
        /// </summary>
        [Fact]
        public void OrderValueIncVatTest()
        {
            // TODO unit test for the property 'OrderValueIncVat'
        }
        /// <summary>
        /// Test the property 'OrderValueExVat'
        /// </summary>
        [Fact]
        public void OrderValueExVatTest()
        {
            // TODO unit test for the property 'OrderValueExVat'
        }
        /// <summary>
        /// Test the property 'ItemValueIncVat'
        /// </summary>
        [Fact]
        public void ItemValueIncVatTest()
        {
            // TODO unit test for the property 'ItemValueIncVat'
        }
        /// <summary>
        /// Test the property 'ItemValueExVat'
        /// </summary>
        [Fact]
        public void ItemValueExVatTest()
        {
            // TODO unit test for the property 'ItemValueExVat'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Fact]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
        /// <summary>
        /// Test the property 'DiscountExVat'
        /// </summary>
        [Fact]
        public void DiscountExVatTest()
        {
            // TODO unit test for the property 'DiscountExVat'
        }
        /// <summary>
        /// Test the property 'FromBalance'
        /// </summary>
        [Fact]
        public void FromBalanceTest()
        {
            // TODO unit test for the property 'FromBalance'
        }
        /// <summary>
        /// Test the property 'ShippingFee'
        /// </summary>
        [Fact]
        public void ShippingFeeTest()
        {
            // TODO unit test for the property 'ShippingFee'
        }
        /// <summary>
        /// Test the property 'ShippingFeeExVat'
        /// </summary>
        [Fact]
        public void ShippingFeeExVatTest()
        {
            // TODO unit test for the property 'ShippingFeeExVat'
        }
        /// <summary>
        /// Test the property 'PaymentFee'
        /// </summary>
        [Fact]
        public void PaymentFeeTest()
        {
            // TODO unit test for the property 'PaymentFee'
        }
        /// <summary>
        /// Test the property 'PaymentFeeExVat'
        /// </summary>
        [Fact]
        public void PaymentFeeExVatTest()
        {
            // TODO unit test for the property 'PaymentFeeExVat'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'OrderMessages'
        /// </summary>
        [Fact]
        public void OrderMessagesTest()
        {
            // TODO unit test for the property 'OrderMessages'
        }
        /// <summary>
        /// Test the property 'PaymentDetails'
        /// </summary>
        [Fact]
        public void PaymentDetailsTest()
        {
            // TODO unit test for the property 'PaymentDetails'
        }
        /// <summary>
        /// Test the property 'ShippingDetails'
        /// </summary>
        [Fact]
        public void ShippingDetailsTest()
        {
            // TODO unit test for the property 'ShippingDetails'
        }
        /// <summary>
        /// Test the property 'ShippingAddress'
        /// </summary>
        [Fact]
        public void ShippingAddressTest()
        {
            // TODO unit test for the property 'ShippingAddress'
        }
        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Fact]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }
        /// <summary>
        /// Test the property 'Rows'
        /// </summary>
        [Fact]
        public void RowsTest()
        {
            // TODO unit test for the property 'Rows'
        }
        /// <summary>
        /// Test the property 'Refunds'
        /// </summary>
        [Fact]
        public void RefundsTest()
        {
            // TODO unit test for the property 'Refunds'
        }
        /// <summary>
        /// Test the property 'Ip'
        /// </summary>
        [Fact]
        public void IpTest()
        {
            // TODO unit test for the property 'Ip'
        }
        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Fact]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
        /// <summary>
        /// Test the property 'ServiceLocation'
        /// </summary>
        [Fact]
        public void ServiceLocationTest()
        {
            // TODO unit test for the property 'ServiceLocation'
        }
        /// <summary>
        /// Test the property 'CampaignCode'
        /// </summary>
        [Fact]
        public void CampaignCodeTest()
        {
            // TODO unit test for the property 'CampaignCode'
        }
        /// <summary>
        /// Test the property 'CampaignCodeId'
        /// </summary>
        [Fact]
        public void CampaignCodeIdTest()
        {
            // TODO unit test for the property 'CampaignCodeId'
        }
        /// <summary>
        /// Test the property 'Percent'
        /// </summary>
        [Fact]
        public void PercentTest()
        {
            // TODO unit test for the property 'Percent'
        }
        /// <summary>
        /// Test the property 'DesiredDeliveryDate'
        /// </summary>
        [Fact]
        public void DesiredDeliveryDateTest()
        {
            // TODO unit test for the property 'DesiredDeliveryDate'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'CartId'
        /// </summary>
        [Fact]
        public void CartIdTest()
        {
            // TODO unit test for the property 'CartId'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'ExternalOrderStatus'
        /// </summary>
        [Fact]
        public void ExternalOrderStatusTest()
        {
            // TODO unit test for the property 'ExternalOrderStatus'
        }
        /// <summary>
        /// Test the property 'CampaignIds'
        /// </summary>
        [Fact]
        public void CampaignIdsTest()
        {
            // TODO unit test for the property 'CampaignIds'
        }
        /// <summary>
        /// Test the property 'CampaignNames'
        /// </summary>
        [Fact]
        public void CampaignNamesTest()
        {
            // TODO unit test for the property 'CampaignNames'
        }
        /// <summary>
        /// Test the property 'MetaData'
        /// </summary>
        [Fact]
        public void MetaDataTest()
        {
            // TODO unit test for the property 'MetaData'
        }
        /// <summary>
        /// Test the property 'PublicId'
        /// </summary>
        [Fact]
        public void PublicIdTest()
        {
            // TODO unit test for the property 'PublicId'
        }

    }

}
