/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCheckoutOrderRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCheckoutOrderRowTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCheckoutOrderRow
        //private OrderCheckoutOrderRow instance;

        public OrderCheckoutOrderRowTests()
        {
            // TODO uncomment below to create an instance of OrderCheckoutOrderRow
            //instance = new OrderCheckoutOrderRow();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCheckoutOrderRow
        /// </summary>
        [Fact]
        public void OrderCheckoutOrderRowInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCheckoutOrderRow
            //Assert.IsType<OrderCheckoutOrderRow>(instance);
        }


        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Fact]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'DiscountRate'
        /// </summary>
        [Fact]
        public void DiscountRateTest()
        {
            // TODO unit test for the property 'DiscountRate'
        }
        /// <summary>
        /// Test the property 'CartRowId'
        /// </summary>
        [Fact]
        public void CartRowIdTest()
        {
            // TODO unit test for the property 'CartRowId'
        }
        /// <summary>
        /// Test the property 'ProductContainerBuildId'
        /// </summary>
        [Fact]
        public void ProductContainerBuildIdTest()
        {
            // TODO unit test for the property 'ProductContainerBuildId'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'ArticleNumber'
        /// </summary>
        [Fact]
        public void ArticleNumberTest()
        {
            // TODO unit test for the property 'ArticleNumber'
        }
        /// <summary>
        /// Test the property 'Gtin'
        /// </summary>
        [Fact]
        public void GtinTest()
        {
            // TODO unit test for the property 'Gtin'
        }
        /// <summary>
        /// Test the property 'Brand'
        /// </summary>
        [Fact]
        public void BrandTest()
        {
            // TODO unit test for the property 'Brand'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Fact]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Variant'
        /// </summary>
        [Fact]
        public void VariantTest()
        {
            // TODO unit test for the property 'Variant'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'PriceIncVat'
        /// </summary>
        [Fact]
        public void PriceIncVatTest()
        {
            // TODO unit test for the property 'PriceIncVat'
        }
        /// <summary>
        /// Test the property 'PriceExVat'
        /// </summary>
        [Fact]
        public void PriceExVatTest()
        {
            // TODO unit test for the property 'PriceExVat'
        }
        /// <summary>
        /// Test the property 'ExpectedTotalPriceIncVat'
        /// </summary>
        [Fact]
        public void ExpectedTotalPriceIncVatTest()
        {
            // TODO unit test for the property 'ExpectedTotalPriceIncVat'
        }
        /// <summary>
        /// Test the property 'DiscountIncVat'
        /// </summary>
        [Fact]
        public void DiscountIncVatTest()
        {
            // TODO unit test for the property 'DiscountIncVat'
        }
        /// <summary>
        /// Test the property 'DiscountExVat'
        /// </summary>
        [Fact]
        public void DiscountExVatTest()
        {
            // TODO unit test for the property 'DiscountExVat'
        }
        /// <summary>
        /// Test the property 'ExpectedTotalDiscountIncVat'
        /// </summary>
        [Fact]
        public void ExpectedTotalDiscountIncVatTest()
        {
            // TODO unit test for the property 'ExpectedTotalDiscountIncVat'
        }
        /// <summary>
        /// Test the property 'ProductUrl'
        /// </summary>
        [Fact]
        public void ProductUrlTest()
        {
            // TODO unit test for the property 'ProductUrl'
        }
        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Fact]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'CampaignIds'
        /// </summary>
        [Fact]
        public void CampaignIdsTest()
        {
            // TODO unit test for the property 'CampaignIds'
        }
        /// <summary>
        /// Test the property 'CampaignGroupData'
        /// </summary>
        [Fact]
        public void CampaignGroupDataTest()
        {
            // TODO unit test for the property 'CampaignGroupData'
        }
        /// <summary>
        /// Test the property 'CampaignNames'
        /// </summary>
        [Fact]
        public void CampaignNamesTest()
        {
            // TODO unit test for the property 'CampaignNames'
        }
        /// <summary>
        /// Test the property 'ProductPriceCampaignId'
        /// </summary>
        [Fact]
        public void ProductPriceCampaignIdTest()
        {
            // TODO unit test for the property 'ProductPriceCampaignId'
        }
        /// <summary>
        /// Test the property 'ProductPriceListId'
        /// </summary>
        [Fact]
        public void ProductPriceListIdTest()
        {
            // TODO unit test for the property 'ProductPriceListId'
        }

    }

}
