/*
 * Geins Management API
 *
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCheckoutOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCheckoutOrderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCheckoutOrder
        //private OrderCheckoutOrder instance;

        public OrderCheckoutOrderTests()
        {
            // TODO uncomment below to create an instance of OrderCheckoutOrder
            //instance = new OrderCheckoutOrder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCheckoutOrder
        /// </summary>
        [Fact]
        public void OrderCheckoutOrderInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCheckoutOrder
            //Assert.IsType<OrderCheckoutOrder>(instance);
        }


        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'ExternalOrderId'
        /// </summary>
        [Fact]
        public void ExternalOrderIdTest()
        {
            // TODO unit test for the property 'ExternalOrderId'
        }
        /// <summary>
        /// Test the property 'CartId'
        /// </summary>
        [Fact]
        public void CartIdTest()
        {
            // TODO unit test for the property 'CartId'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'SiteId'
        /// </summary>
        [Fact]
        public void SiteIdTest()
        {
            // TODO unit test for the property 'SiteId'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Fact]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'InternalMessage'
        /// </summary>
        [Fact]
        public void InternalMessageTest()
        {
            // TODO unit test for the property 'InternalMessage'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
        /// <summary>
        /// Test the property 'Rows'
        /// </summary>
        [Fact]
        public void RowsTest()
        {
            // TODO unit test for the property 'Rows'
        }
        /// <summary>
        /// Test the property 'CampaignId'
        /// </summary>
        [Fact]
        public void CampaignIdTest()
        {
            // TODO unit test for the property 'CampaignId'
        }
        /// <summary>
        /// Test the property 'CampaignCode'
        /// </summary>
        [Fact]
        public void CampaignCodeTest()
        {
            // TODO unit test for the property 'CampaignCode'
        }
        /// <summary>
        /// Test the property 'CampaignName'
        /// </summary>
        [Fact]
        public void CampaignNameTest()
        {
            // TODO unit test for the property 'CampaignName'
        }
        /// <summary>
        /// Test the property 'CampaignIds'
        /// </summary>
        [Fact]
        public void CampaignIdsTest()
        {
            // TODO unit test for the property 'CampaignIds'
        }
        /// <summary>
        /// Test the property 'CampaignNames'
        /// </summary>
        [Fact]
        public void CampaignNamesTest()
        {
            // TODO unit test for the property 'CampaignNames'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'CustomerTypeId'
        /// </summary>
        [Fact]
        public void CustomerTypeIdTest()
        {
            // TODO unit test for the property 'CustomerTypeId'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [Fact]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }
        /// <summary>
        /// Test the property 'PersonalId'
        /// </summary>
        [Fact]
        public void PersonalIdTest()
        {
            // TODO unit test for the property 'PersonalId'
        }
        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Fact]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
        /// <summary>
        /// Test the property 'MetaData'
        /// </summary>
        [Fact]
        public void MetaDataTest()
        {
            // TODO unit test for the property 'MetaData'
        }
        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Fact]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'SecondaryTransactionId'
        /// </summary>
        [Fact]
        public void SecondaryTransactionIdTest()
        {
            // TODO unit test for the property 'SecondaryTransactionId'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'OrganizationNumber'
        /// </summary>
        [Fact]
        public void OrganizationNumberTest()
        {
            // TODO unit test for the property 'OrganizationNumber'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Address1'
        /// </summary>
        [Fact]
        public void Address1Test()
        {
            // TODO unit test for the property 'Address1'
        }
        /// <summary>
        /// Test the property 'Address2'
        /// </summary>
        [Fact]
        public void Address2Test()
        {
            // TODO unit test for the property 'Address2'
        }
        /// <summary>
        /// Test the property 'Zip'
        /// </summary>
        [Fact]
        public void ZipTest()
        {
            // TODO unit test for the property 'Zip'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'MobilePhone'
        /// </summary>
        [Fact]
        public void MobilePhoneTest()
        {
            // TODO unit test for the property 'MobilePhone'
        }
        /// <summary>
        /// Test the property 'CareOf'
        /// </summary>
        [Fact]
        public void CareOfTest()
        {
            // TODO unit test for the property 'CareOf'
        }
        /// <summary>
        /// Test the property 'ShippingId'
        /// </summary>
        [Fact]
        public void ShippingIdTest()
        {
            // TODO unit test for the property 'ShippingId'
        }
        /// <summary>
        /// Test the property 'ShippingCountry'
        /// </summary>
        [Fact]
        public void ShippingCountryTest()
        {
            // TODO unit test for the property 'ShippingCountry'
        }
        /// <summary>
        /// Test the property 'ShippingCompany'
        /// </summary>
        [Fact]
        public void ShippingCompanyTest()
        {
            // TODO unit test for the property 'ShippingCompany'
        }
        /// <summary>
        /// Test the property 'ShippingOrganizationNumber'
        /// </summary>
        [Fact]
        public void ShippingOrganizationNumberTest()
        {
            // TODO unit test for the property 'ShippingOrganizationNumber'
        }
        /// <summary>
        /// Test the property 'ShippingFirstName'
        /// </summary>
        [Fact]
        public void ShippingFirstNameTest()
        {
            // TODO unit test for the property 'ShippingFirstName'
        }
        /// <summary>
        /// Test the property 'ShippingLastName'
        /// </summary>
        [Fact]
        public void ShippingLastNameTest()
        {
            // TODO unit test for the property 'ShippingLastName'
        }
        /// <summary>
        /// Test the property 'ShippingEmail'
        /// </summary>
        [Fact]
        public void ShippingEmailTest()
        {
            // TODO unit test for the property 'ShippingEmail'
        }
        /// <summary>
        /// Test the property 'ShippingAddress1'
        /// </summary>
        [Fact]
        public void ShippingAddress1Test()
        {
            // TODO unit test for the property 'ShippingAddress1'
        }
        /// <summary>
        /// Test the property 'ShippingAddress2'
        /// </summary>
        [Fact]
        public void ShippingAddress2Test()
        {
            // TODO unit test for the property 'ShippingAddress2'
        }
        /// <summary>
        /// Test the property 'ShippingZip'
        /// </summary>
        [Fact]
        public void ShippingZipTest()
        {
            // TODO unit test for the property 'ShippingZip'
        }
        /// <summary>
        /// Test the property 'ShippingCity'
        /// </summary>
        [Fact]
        public void ShippingCityTest()
        {
            // TODO unit test for the property 'ShippingCity'
        }
        /// <summary>
        /// Test the property 'ShippingRegion'
        /// </summary>
        [Fact]
        public void ShippingRegionTest()
        {
            // TODO unit test for the property 'ShippingRegion'
        }
        /// <summary>
        /// Test the property 'ShippingPhone'
        /// </summary>
        [Fact]
        public void ShippingPhoneTest()
        {
            // TODO unit test for the property 'ShippingPhone'
        }
        /// <summary>
        /// Test the property 'ShippingMobilePhone'
        /// </summary>
        [Fact]
        public void ShippingMobilePhoneTest()
        {
            // TODO unit test for the property 'ShippingMobilePhone'
        }
        /// <summary>
        /// Test the property 'ShippingCareOf'
        /// </summary>
        [Fact]
        public void ShippingCareOfTest()
        {
            // TODO unit test for the property 'ShippingCareOf'
        }
        /// <summary>
        /// Test the property 'PickupPoint'
        /// </summary>
        [Fact]
        public void PickupPointTest()
        {
            // TODO unit test for the property 'PickupPoint'
        }
        /// <summary>
        /// Test the property 'DesiredDeliveryDate'
        /// </summary>
        [Fact]
        public void DesiredDeliveryDateTest()
        {
            // TODO unit test for the property 'DesiredDeliveryDate'
        }
        /// <summary>
        /// Test the property 'FreightClass'
        /// </summary>
        [Fact]
        public void FreightClassTest()
        {
            // TODO unit test for the property 'FreightClass'
        }
        /// <summary>
        /// Test the property 'Sum'
        /// </summary>
        [Fact]
        public void SumTest()
        {
            // TODO unit test for the property 'Sum'
        }
        /// <summary>
        /// Test the property 'ExpectedSum'
        /// </summary>
        [Fact]
        public void ExpectedSumTest()
        {
            // TODO unit test for the property 'ExpectedSum'
        }
        /// <summary>
        /// Test the property 'OrderValueIncVat'
        /// </summary>
        [Fact]
        public void OrderValueIncVatTest()
        {
            // TODO unit test for the property 'OrderValueIncVat'
        }
        /// <summary>
        /// Test the property 'OrderValueExVat'
        /// </summary>
        [Fact]
        public void OrderValueExVatTest()
        {
            // TODO unit test for the property 'OrderValueExVat'
        }
        /// <summary>
        /// Test the property 'ItemValueIncVat'
        /// </summary>
        [Fact]
        public void ItemValueIncVatTest()
        {
            // TODO unit test for the property 'ItemValueIncVat'
        }
        /// <summary>
        /// Test the property 'ItemValueExVat'
        /// </summary>
        [Fact]
        public void ItemValueExVatTest()
        {
            // TODO unit test for the property 'ItemValueExVat'
        }
        /// <summary>
        /// Test the property 'DiscountIncVat'
        /// </summary>
        [Fact]
        public void DiscountIncVatTest()
        {
            // TODO unit test for the property 'DiscountIncVat'
        }
        /// <summary>
        /// Test the property 'DiscountExVat'
        /// </summary>
        [Fact]
        public void DiscountExVatTest()
        {
            // TODO unit test for the property 'DiscountExVat'
        }
        /// <summary>
        /// Test the property 'PercentDiscount'
        /// </summary>
        [Fact]
        public void PercentDiscountTest()
        {
            // TODO unit test for the property 'PercentDiscount'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'ShippingFeeIncVat'
        /// </summary>
        [Fact]
        public void ShippingFeeIncVatTest()
        {
            // TODO unit test for the property 'ShippingFeeIncVat'
        }
        /// <summary>
        /// Test the property 'ShippingFeeExVat'
        /// </summary>
        [Fact]
        public void ShippingFeeExVatTest()
        {
            // TODO unit test for the property 'ShippingFeeExVat'
        }
        /// <summary>
        /// Test the property 'PaymentFeeIncVat'
        /// </summary>
        [Fact]
        public void PaymentFeeIncVatTest()
        {
            // TODO unit test for the property 'PaymentFeeIncVat'
        }
        /// <summary>
        /// Test the property 'PaymentFeeExVat'
        /// </summary>
        [Fact]
        public void PaymentFeeExVatTest()
        {
            // TODO unit test for the property 'PaymentFeeExVat'
        }

    }

}
